#!/usr/bin/env bash
echo '{"text":"󰈤 OpSec","tooltip":"🔒 OpSec Cleaner • Dijital Parmak İzi Sanitizörü\n• JPEG/PNG görsellerindeki GPS, kamera ve kullanıcı izlerini sıfırlar.\n\n[Sol Tık] Görsel Seç ve Temizle","class":"normal"}'
